use_frameworks!

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'SwiftUISample' do
  platform :ios, '13.0'

  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseAuth', :path => '../../'

end
